version: '3'
services:
  sellerpannelservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sellerpannelservice
    restart: always
    ports:
      - "8089:80"
    networks:
      sellerpannel:
        ipv4_address: 172.28.0.2

networks:
  sellerpannel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
